### ISSUE TITLE
Python 3 error in runningMean()

### ISSUE THREAD

**Issue by const-ae** [statisticalbiotechnology/triqler#12]
Hi Matthew,

I noticed that under Python 3 the `runningMean()` fails on [line 70](https://github.com/statisticalbiotechnology/triqler/blob/master/triqler/convert/normalize_intensities.py#L70) with an error message: 

```
TypeError: can't multiply sequence by non-int of type 'float'
```

I believe this is due to a change how Python 3 handles int and float conversions:

![image](https://user-images.githubusercontent.com/5359014/80481717-461fc700-8953-11ea-8a3c-c74b6f2c8898.png)

Best, Constantin

**Comment by MatthewThe** [comment]
Thanks for reporting this! Strange that I haven't encountered this error before even with Python3. I'll see if I can reproduce the error, but I guess there is no harm in adding the extra `int()` regardless.

**Comment by MatthewThe** [comment]
I could indeed reproduce the error, and adding the `int()` function indeed solved the problem. Thanks again for the help!
