### ISSUE TITLE
Calculating PEPs can be extremely slow due to numpy OMP multiprocessing

### ISSUE THREAD

**Issue by MatthewThe** [statisticalbiotechnology/triqler#13]
On some systems (e.g. Ubuntu), calculating PEPs with getQvaluesFromScores is extremely slow (more than 1 minute instead of just a few seconds) when OMP multithreading is not disabled for numpy. This can be circumvented by prepending the call to Triqler/Qvality by `OMP_NUM_THREADS=1`. I'm not sure yet which of the numpy functions is causing this, but it's most likely one of the matrix functions used in the IRLS.

https://github.com/statisticalbiotechnology/triqler/blob/b433f7bf148b6b4d90a09c0d8469712281badf95/triqler/qvality.py#L28

**Comment by wfondrie** [comment]
@MatthewThe - any idea on a timeline for a new release containing this PR?

**Comment by MatthewThe** [comment]
Sorry, updating the package is indeed long overdue. I will try to make a new release tomorrow.
