### ISSUE TITLE
Issues running triqler on example iPRG2016.tsv data

### ISSUE THREAD

**Issue by magnuspalmblad** [statisticalbiotechnology/triqler#2]
Dear Matthew,

I just installed and tried triqler on the example data, but get the error below. Any idea what could cause this? I run Python 3.6.4. and Anaconda under Windows 10.

The error message:
(base) C:\Users\Magnus Palmblad\Documents>head -3 iPRG2016.tsv
run     condition       charge  searchScore     intensity       peptide proteins
A1.ms2  1:A+B   2       -1.39236        394249806.7249588       K.LLEGPTVTDR.L  decoy_HPRR4310048_entrapment
A2.ms2  1:A+B   2       -1.39838        445444704.9268748       K.LLEGPTVTDR.L  decoy_HPRR4310048_entrapment

(base) C:\Users\Magnus Palmblad\Documents>tail -3 iPRG2016.tsv
C1.ms2  3:A     3       -1.45912        12915789.487361887      K.TLEFLPRPRPSANRQR.L    HPRR4320022_entrapment
C2.ms2  3:A     3       -1.55708        5550268.634351935       K.TLEFLPRPRPSANRQR.L    HPRR4320022_entrapment
C3.ms2  3:A     3       -1.44732        7446522.421254935       K.TLEFLPRPRPSANRQR.L    HPRR4320022_entrapment

(base) C:\Users\Magnus Palmblad\Documents>python -m triqler --fold_change_eval 0.8 iPRG2016.tsv
Triqler version 0.1.2
Copyright (c) 2018 Matthew The. All rights reserved.
Written by Matthew The (matthew.the@scilifelab.se) in the
School of Engineering Sciences in Chemistry, Biotechnology and Health at the
Royal Institute of Technology in Stockholm.

Parsing triqler input file
Calculating identification PEPs
featureClusterIdx: 0
featureClusterIdx: 10000
Dividing intensities by 100000 for increased readability
Surviving spectrumIdxs: 12452
Converting to peptide quant rows
Calculating peptide-level identification PEPs
Writing peptide quant rows to file
Fitting hyperparameters
params["muDetect"], params["sigmaDetect"] = 1.048101, 0.376365
params["muXIC"], params["sigmaXIC"] = 3.277408, 0.951171
params["muProtein"], params["sigmaProtein"] = 0.066833, 0.239527
params["muFeatureDiff"], params["sigmaFeatureDiff"] = -0.014124, 0.148583
params["shapeInGroupStdevs"], params["scaleInGroupStdevs"] = 1.027202, 0.089210
Calculating protein quants
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\triqler\__main__.py", line 8, in <module>
    main()
  File "C:\Anaconda3\lib\site-packages\triqler\triqler.py", line 35, in main
    runTriqler(params, args.in_file, args.out_file)
  File "C:\Anaconda3\lib\site-packages\triqler\triqler.py", line 102, in runTriqler
    diff_exp.doDiffExp(params, peptQuantRows, triqlerOutputFile, getPickedProteinCalibration, selectComparisonBayesTmp, qvalMethod = qvalMethod)
  File "C:\Anaconda3\lib\site-packages\triqler\diff_exp.py", line 17, in doDiffExp
    proteinOutputRows = proteinQuantificationMethod(peptQuantRows, params, proteinModifier, getEvalFeatures)
  File "C:\Anaconda3\lib\site-packages\triqler\triqler.py", line 360, in getPickedProteinCalibration
    posteriors = processingPool.checkPool(printProgressEvery = 50)
  File "C:\Anaconda3\lib\site-packages\triqler\multiprocessing_pool.py", line 19, in checkPool
    outputs.append(res.get(0xFFFFFFFF))
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 638, in get
    self.wait(timeout)
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 635, in wait
    self._event.wait(timeout)
  File "C:\Anaconda3\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Anaconda3\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

**Comment by MatthewThe** [comment]
Dear Magnus,

Thanks for reporting this, apparently the `multiprocessing` module has [some restrictions](https://docs.python.org/2.7/library/multiprocessing.html#windows) on Windows which I haven't taken into account. I will have a look if I can fix this, or otherwise provide an option to disable the multiprocessing module.

**Comment by MatthewThe** [comment]
Dear Magnus,

I think I managed to fix the error and just created a new release (0.1.3) that should be installable with `pip install --upgrade triqler` (I had to upgrade the pip package to 0.18 for the `--upgrade` to work). Could you try if that fixes it for you?
