### ISSUE TITLE
PEPs are constant one for certain inputs

### ISSUE THREAD

**Issue by ezander** [statisticalbiotechnology/triqler#28]
For certain inputs of `scores` and `targets` the peps computed by `getQvaluesFromScores` are all one. This is due to the monotonization step at the end of the function (line 81, `probs = monotonize(probs)`). 

I've created a fork at https://github.com/ezander/triqler and added two files (data.py and issue.py) in https://github.com/ezander/triqler/tree/issue/pep_constant_one/tests/issue that demonstrate the issue.

**Comment by RalfG** [comment]
We have also seen this happening when the highest scoring PSM is a decoy. As a workaround (but obviously not a fix), such decoy PSMs could be removed from the dataset.

**Comment by MatthewThe** [comment]
An alternative way to compute PEPs using non-negative least squares should resolve this problem and is now implemented in Mokapot:
https://github.com/wfondrie/mokapot/blob/6b8fbfd20c97c6918673fbbf37f9cd77faad500c/mokapot/peps.py#L201

I will not actively try to find a fix for Triqler's IRLS implementation of PEP calculation, as most people encountering this problem were experiencing this problem through Mokapot.

In the future, it may be worth to isolate the different PEP calculation functions in a separate Python package that can then be imported by both mokapot and triqler.
