### ISSUE TITLE
Still getting errors (but different ones)!

### ISSUE THREAD

**Issue by magnuspalmblad** [statisticalbiotechnology/triqler#3]
Dear Matthew,

I updated triqler and tried it again. I do get the results, but also some warnings that you may be interested in:

[Anaconda3] C:\Users\nmpalmblad\My Documents\Projects\triqler>triqler --fold_cha
nge_eval 0.8 iPRG2016.tsv
Triqler version 0.1.3
Copyright (c) 2018 Matthew The. All rights reserved.
Written by Matthew The (matthew.the@scilifelab.se) in the
School of Engineering Sciences in Chemistry, Biotechnology and Health at the
Royal Institute of Technology in Stockholm.

Parsing triqler input file
Calculating identification PEPs
featureClusterIdx: 0
featureClusterIdx: 10000
Dividing intensities by 100000 for increased readability
Surviving spectrumIdxs: 12452
Converting to peptide quant rows
Calculating peptide-level identification PEPs
Writing peptide quant rows to file
Fitting hyperparameters
params["muDetect"], params["sigmaDetect"] = 1.048101, 0.376366
params["muXIC"], params["sigmaXIC"] = 3.277408, 0.951171
params["muProtein"], params["sigmaProtein"] = 0.066833, 0.239527
params["muFeatureDiff"], params["sigmaFeatureDiff"] = -0.014124, 0.148583
params["shapeInGroupStdevs"], params["scaleInGroupStdevs"] = 1.027202, 0.089210
Calculating protein quants
Traceback (most recent call last):
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\runpy.py", lin
e 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\runpy.py", lin
e 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\nmpalmblad\AppData\Local\Continuum\Anaconda3\Scripts\triqler.ex
e\__main__.py", line 9, in <module>
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\
triqler\triqler.py", line 35, in main
    runTriqler(params, args.in_file, args.out_file)
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\
triqler\triqler.py", line 102, in runTriqler
    diff_exp.doDiffExp(params, peptQuantRows, triqlerOutputFile, getPickedProtei
nCalibration, selectComparisonBayesTmp, qvalMethod = qvalMethod)
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\
triqler\diff_exp.py", line 17, in doDiffExp
    proteinOutputRows = proteinQuantificationMethod(peptQuantRows, params, prote
inModifier, getEvalFeatures)
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\
triqler\triqler.py", line 360, in getPickedProteinCalibration
    posteriors = processingPool.checkPool(printProgressEvery = 50)
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\
triqler\multiprocessing_pool.py", line 19, in checkPool
    outputs.append(res.get(True))
  File "c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\multiprocessin
g\pool.py", line 604, in get
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in g
reater_equal
  return (self.a <= x) & (x <= self.b)
    raise TimeoutError
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in l
ess_equal
  return (self.a <= x) & (x <= self.b)
multiprocessing.context.TimeoutError
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in g
reater_equal
  return (self.a <= x) & (x <= self.b)
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in l
ess_equal
  return (self.a <= x) & (x <= self.b)
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in g
reater_equal
  return (self.a <= x) & (x <= self.b)
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in l
ess_equal
  return (self.a <= x) & (x <= self.b)
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in g
reater_equal
  return (self.a <= x) & (x <= self.b)
c:\users\nmpalmblad\appdata\local\continuum\anaconda3\lib\site-packages\scipy\st
ats\_distn_infrastructure.py:876: RuntimeWarning: invalid value encountered in l
ess_equal
  return (self.a <= x) & (x <= self.b)

[Anaconda3] C:\Users\nmpalmblad\My Documents\Projects\triqler>

**Comment by MatthewThe** [comment]
Dear Magnus,

Thanks for reporting this. It's safe to ignore these warnings but I'll try to find a way to avoid them.
