### ISSUE TITLE
ERROR: At least two conditions (treatment groups) should be specified.

### ISSUE THREAD

**Issue by yafeng** [statisticalbiotechnology/triqler#30]
Hi, While I am trying out Triqler for my data, it returns an error which I don't understand because I have specified two conditions in my file. Could you help me on it? Thanks a lot!

"
python3 -m triqler --fold_change_eval 0.8 threeProteome-mix-triqler-input.txt
Triqler version 0.7.3
Copyright (c) 2018-2024 Matthew The, Patrick Truong. All rights reserved.
Written by:
- Matthew The (matthew.the@scilifelab.se)
- Patrick Truong (patrick.truong@scilifelab.se)
in the School of Engineering Sciences in Chemistry, Biotechnology and Health
at the Royal Institute of Technology in Stockholm.
Issued command: triqler.py --fold_change_eval 0.8 threeProteome-mix-triqler-input.txt
Parsing triqler input file
  Reading row 0
ERROR: At least two conditions (treatment groups) should be specified.
"
My in input file looks like this. It contains two conditions, A and B.   I don't know why the code says "ERROR: At least two conditions (treatment groups) should be specified." 

`

run	condition	charge	searchScore	intensity	peptide	proteins
r1	A	2	0.551910758018494	17545.1171875	NNEETVMSAR	A0A024QZ33;Q9H0G5
r1	A	3	0.626867949962616	4289.80029296875	NQEKPSNSESSLGAK	A0A024QZ33;Q9H0G5
r1	A	3	0.721568584442139	21148.537109375	FCADHPFLFFIQHSK	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237
r1	A	4	0.553977787494659	21148.537109375	FCADHPFLFFIQHSK	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237
r1	A	2	0.737841725349426	73623.65625	TNGILFCGR	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237
r1	A	2	0.701564610004425	64660.67578125	HINTWVAEK	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237
r1	A	3	0.659828424453735	26185.087890625	KHINTWVAEK	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237
r1	A	2	0.6534064412117	26185.087890625	KHINTWVAEK	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237
r1	A	2	0.739094197750092	192524.78125	LVLVNAVYFR	A0A024QZX5;A0A087X1N8;A0A2R8YD12;P35237`

**Comment by MatthewThe** [comment]
That's odd, would it be possible to share the entire input file? In the few lines you posted there's only one condition.

**Comment by yafeng** [comment]
@MatthewThe Thanks! Here is the entire input file. The condition A and B both have three replicates r1, r2, and r3.
[threeProteome-mix-triqler-input.txt.zip](https://github.com/user-attachments/files/17986013/threeProteome-mix-triqler-input.txt.zip)

**Comment by MatthewThe** [comment]
the problem is that you should not reuse the names r1, r2, r3 in the second condition.
Naming your runs A_r1, A_r2, A_r3, B_r1, B_r2, B_r3 should resolve the problem.

I will add a better error message for this situation.
