### ISSUE TITLE
What other search scores we can use for Triqler?

### ISSUE THREAD

**Issue by weixiandeng** [statisticalbiotechnology/triqler#5]
Hi Matt,

For the searchScore column in the input file, except for percolator score, what other search scores we can use here, for example, if we use MaxQuant, can I use the Score column from MSMS.txt file?

Best,
Weixian

**Comment by MatthewThe** [comment]
Hi Weixian,

In theory, you should be able to use any search engine score, just make sure that higher scores mean more confident identifications (or multiply by -1 otherwise). We have, however, not tested this with other scores than percolator's, but I would be very interested in your results.

**Comment by weixiandeng** [comment]
Hi Mattew,

Thanks for your reply, I'll let you know once I have some results. Since the first glance at your paper, I noticed you did feature extraction at the very begining and mapped to PSM afterwards, so that reminded me of MaxQuant, but it should also work for Skyline-based quantitation pipelines, right? As long as we build the spectrum library with non-filtered PSM, and then extract PSM-intensity pairs which passed mprophet filter. Do you have any test for this kind of pipelines?

**Comment by MatthewThe** [comment]
I'm not too familiar with the Skyline pipeline so I can't help you too much with that at the moment. However, if you think this would really be a good idea, we can discuss it in some more detail by e-mail.

**Comment by weixiandeng** [comment]
I failed to find the full decoy search result which means I only found very few decoy  from MaxQuant, even searched with decoy concatted database. Do you have any idea if Andomeda gives the intermediate result?

**Comment by MatthewThe** [comment]
Sorry for the very late reply. As far as I could tell there are no (readable) intermediate files from Andromeda that could provide enough decoy information. Unfortunately, neither the msms.txt nor the allPeptides.txt provided the needed information. I have not checked yet if one could change some search parameters to obtain this, e.g. setting the FDR threshold to 1.0.

**Comment by MatthewThe** [comment]
As it turns out, there was a file called `evidence.txt` that seemed to contain sufficient information to run Triqler. I have added a converter for this file to the Triqler package: https://github.com/statisticalbiotechnology/triqler/wiki/Converters

We recommended setting the MaxQuant FDR threshold to 100% for best performance, though it usually also works with the default thresholds of 1% FDR.
